site_name: Arista EVPN Deployment Guide

nav:
  - Home: index.md
  - Data Center A: datacenter_a.md
  - Data Center B: datacenter_b.md
  - Data Center C: datacenter_c.md
  - DCI: dci.md
  - Additional Resources: additional_resources.md

copyright: Copyright &copy; 2022 Restless Wanderer

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date
  - search:
      lang: en

repo_name: Arista IPSec VPN Guide on GitHub

repo_url: https://github.com/restlesswanderer/ipsec

theme:

  features:
    - content.code.annotate
    - content.tooltips
    - header.autohide
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate

  favicon: assets/images/logo.png

  font:
    text: Roboto
    code: Fira Mono

  language: en

  logo: assets/images/logo.png

  name: material
  
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode